Syslog                  yes
SyslogSuccess           yes
LogWhy                  yes

Canonicalization        relaxed/simple
Domain                  mattjack.cloud
Selector                mail
KeyFile                 /etc/opendkim/keys/mattjack.cloud/mail.private

SignHeaders             From,To,Subject,Date,Message-ID,MIME-Version,Content-Type
OversignHeaders         From

Socket inet:8891@localhost
PidFile                 /run/opendkim/opendkim.pid
UMask                   007
UserID                  opendkim

TrustAnchorFile         /usr/share/dns/root.key
